// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzYoZOT9G3U9hGhONDEUVTkFnJmo_gyLU',
    appId: '1:985978777293:web:4766069504f77d220a0384',
    messagingSenderId: '985978777293',
    projectId: 'ecommerceapp-96644',
    authDomain: 'ecommerceapp-96644.firebaseapp.com',
    storageBucket: 'ecommerceapp-96644.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc9He6_y8qQl0uOxjAEt8QUoja1BZfrgo',
    appId: '1:985978777293:android:4e400fcbdef5e8100a0384',
    messagingSenderId: '985978777293',
    projectId: 'ecommerceapp-96644',
    storageBucket: 'ecommerceapp-96644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEfjYe-BURNamCdku0xSZXcOdQresV-Sw',
    appId: '1:985978777293:ios:3baf92c577332b580a0384',
    messagingSenderId: '985978777293',
    projectId: 'ecommerceapp-96644',
    storageBucket: 'ecommerceapp-96644.appspot.com',
    androidClientId: '985978777293-ij9pcjinrin376c40mki8775r3vdr7vs.apps.googleusercontent.com',
    iosClientId: '985978777293-b5hkg874mc1720fqk8vjvfqhl3urj7tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceapp',
  );
}
